jwt:
  secret:
    key: iamsubo
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 196500276982-7amtip1avjo5hhdlk63tnrns4d7u3tpc.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile